# ansible/install_dependencies.yml
- hosts: webserver
  remote_user: pelin
  become_method: dzdo
  become: yes
  vars:
    ansible_ssh_private_key_file: /home/pelin/.ssh/id_rsa
    ansible_become_password: pelin
    ansible_python_interpreter: /usr/share/python3
  tasks:
    - name: Ensure Python 3 and pip are installed
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

    - name: Install required Python packages
      pip:
        name: ansible
        executable: pip3

    - name: Install six module
      pip:
        name: six
        executable: pip3

    - name: Ensure six module is installed in the correct Python environment
      command: python3 -m pip install six
