- hosts: webserver
  remote_user: pelin
  become: yes
  vars:
    ansible_ssh_private_key_file: /home/pelin/.ssh/id_rsa
    ansible_become_password: pelin

  tasks:
      - name: Gather facts
        ansible.builtin.setup:
      - name: Ensure Python 3 and pip are installed
        apt:
          name: "{{ item }}"
          state: present
        loop:
          - python3
          - python3-pip

      - name: Install required Python packages
        pip:
          name: ansible
          executable: pip3

      - name: Install Docker
        apt:
          name: docker.io
          state: present

      - name: Install Docker Python Module
        pip:
          name: docker
          executable: pip3

      - name: Pull Docker Image
        docker_image:
          name: pelino250/flask-project
          source: pull

      - name: Run Docker Container
        docker_container:
          name: flask-project-demo
          image: pelino250/devops-demo
#          ports:
#            - "5000:5000"
          state: started